-- =============================================================================
-- Phase 11 — Dish Enrichment: Add enrichment columns to menu_items
-- =============================================================================
-- Adds 7 enrichment columns for cultural context data generated by the
-- batch LLM enrichment pipeline (lib/enrichment.ts).
-- All columns nullable — safe for existing rows with no enrichment yet.
-- Partial index idx_menu_items_enrichment_pending already exists from Phase 10.
-- =============================================================================

ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS enrichment_origin TEXT;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS enrichment_ingredients TEXT[];
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS enrichment_cultural_note TEXT;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS enrichment_eating_tips TEXT;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS enrichment_depth TEXT;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS enrichment_model TEXT;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS enriched_at TIMESTAMPTZ;
